2022-01-20 22:41:20,126 INFO    Thread-2  :15909 [wandb_setup.py:_flush():71] setting env: {'entity': 'amazonproject', 'project': 'Amazon-Reviews-local', 'root_dir': '/Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project', 'sweep_id': 'auvymncv', 'run_id': 'm5066tbe', 'sweep_param_path': '/Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project/wandb/sweep-auvymncv/config-m5066tbe.yaml'}
2022-01-20 22:41:20,127 WARNING Thread-2  :15909 [wandb_setup.py:_flush():71] could not save program above cwd: /Users/augustehlers/miniconda3/envs/p37/lib/python3.7/cProfile.py
2022-01-20 22:41:20,127 INFO    Thread-2  :15909 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-20 22:41:20,127 INFO    Thread-2  :15909 [wandb_init.py:_log_setup():371] Logging user logs to /Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project/wandb/run-20220120_224120-m5066tbe/logs/debug.log
2022-01-20 22:41:20,127 INFO    Thread-2  :15909 [wandb_init.py:_log_setup():372] Logging internal logs to /Users/augustehlers/OneDrive - Danmarks Tekniske Universitet/Studiemappe/11. semester/MLOps/MLOps_Amazon_review_project/wandb/run-20220120_224120-m5066tbe/logs/debug-internal.log
2022-01-20 22:41:20,128 INFO    Thread-2  :15909 [wandb_init.py:init():404] calling init triggers
2022-01-20 22:41:20,128 INFO    Thread-2  :15909 [wandb_init.py:init():411] wandb.init called with sweep_config: {'batch_size': 75, 'drop_out': 0.35, 'lr': 0.01, 'optimizer': 'sgd'}
config: {}
2022-01-20 22:41:20,128 INFO    Thread-2  :15909 [wandb_init.py:init():460] starting backend
2022-01-20 22:41:20,128 INFO    Thread-2  :15909 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-20 22:41:20,144 INFO    Thread-2  :15909 [backend.py:ensure_launched():216] starting backend process...
2022-01-20 22:41:20,162 INFO    Thread-2  :15909 [backend.py:ensure_launched():222] started backend process with pid: 15919
2022-01-20 22:41:20,166 INFO    Thread-2  :15909 [wandb_init.py:init():469] backend started and connected
2022-01-20 22:41:20,169 INFO    Thread-2  :15909 [wandb_run.py:_config_callback():956] config_cb None None {'batch_size': 75, 'drop_out': 0.35, 'lr': 0.01, 'optimizer': 'sgd'}
2022-01-20 22:41:20,175 INFO    Thread-2  :15909 [wandb_init.py:init():533] updated telemetry
2022-01-20 22:41:20,222 INFO    Thread-2  :15909 [wandb_init.py:init():563] communicating current version
2022-01-20 22:41:21,446 INFO    Thread-2  :15909 [wandb_init.py:init():568] got version response 
2022-01-20 22:41:21,446 INFO    Thread-2  :15909 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-20 22:41:21,681 INFO    Thread-2  :15909 [wandb_init.py:init():606] starting run threads in backend
2022-01-20 22:41:23,669 INFO    Thread-2  :15909 [wandb_run.py:_console_start():1810] atexit reg
2022-01-20 22:41:23,670 INFO    Thread-2  :15909 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.REDIRECT
2022-01-20 22:41:23,670 INFO    Thread-2  :15909 [wandb_run.py:_redirect():1689] Redirecting console.
2022-01-20 22:41:23,670 ERROR   Thread-2  :15909 [wandb_run.py:_redirect():1748] Failed to redirect.
Traceback (most recent call last):
  File "/Users/augustehlers/miniconda3/envs/p37/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1741, in _redirect
    out_redir.install()
  File "/Users/augustehlers/miniconda3/envs/p37/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 709, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/Users/augustehlers/miniconda3/envs/p37/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 659, in add_fd
    self._register()
  File "/Users/augustehlers/miniconda3/envs/p37/lib/python3.7/site-packages/wandb/sdk/lib/redirect.py", line 644, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/Users/augustehlers/miniconda3/envs/p37/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-01-20 22:41:23,672 INFO    Thread-2  :15909 [wandb_init.py:init():633] run started, returning control to user process
2022-01-20 22:43:55,304 INFO    Thread-2  :15909 [wandb_run.py:finish():1457] finishing run amazonproject/Amazon-Reviews-local/m5066tbe
2022-01-20 22:43:55,356 INFO    Thread-2  :15909 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 1
2022-01-20 22:43:55,357 INFO    Thread-2  :15909 [wandb_run.py:_restore():1752] restore
